name: Go fmt

on: [push]

jobs:
  gofmt:
    name: Format Go code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Run go fmt
        run: go fmt ./...
