name: golangci-lint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PARAMETERS: ${{ secrets.DB_PARAMETERS }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.7

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.54.1
          args: --timeout 5m
          fix: true
